### ISSUE TITLE
Project init causing Error: ENOENT: no such file or directory, mkdir

### ISSUE THREAD

**Issue by ieshan** [mintlify/mint#22]
I am trying to init the project using the following command

```bash
npx mintlify init
```

Getting `Error: ENOENT: no such file or directory, mkdir` during following `createPage` call

https://github.com/mintlify/mint/blob/83cb73c4ee5bbd1f326e97855a2832623b0deb06/cli/src/index.ts#L107

It seems like the error is happening in the following section, possibly because `rootDir` is empty in this part
https://github.com/mintlify/mint/blob/83cb73c4ee5bbd1f326e97855a2832623b0deb06/cli/src/util.ts#L44

This would also give error for
```bash
npx mintlify page
```

**Comment by hahnbeelee** [comment]
Hey @ieshan, We're super excited to see your interest in the mint repo. 

Despite this repo being public we're still in the midst of ironing out self-hosting. I'll let you know once we release the infrastructure and documentation for self-hosting projects from this repo! What you've stumbled upon is our internal CLI that we use to automate our process of migrating customers.

**Comment by tobias-mintlify** [comment]
Closing because we made a [template repo](https://github.com/mintlify/starter) and deprecated the `init` command.
