### ISSUE TITLE
Popin of Code groups

### ISSUE THREAD

**Issue by NicoZweifel** [mintlify/mint#269]
**Describe the bug**
Pop-in of CodeGroup

**To Reproduce**
go here: https://mintlify.com/docs/development
or here: https://mintlify.com/docs/components/card-group
and refresh.

**Expected behavior**
No pop-in and no hydration errors.

**Device:**
 - OS: Windows 10
 - chrome
 - 109.0.5414.119 (Official Build) (64-bit)

Hydration errors in the normal Code Blocks were fixed (except `jsx`, `tsx`) - tracked in a different [issue](https://github.com/mintlify/mint/issues/258).
The popins of the basic CodeBlock without group were fixed in https://github.com/mintlify/components/pull/39.
But for groups it still persists.

**Comment by tobias-mintlify** [comment]
I'm making a PR within the next two days connecting Nico's work to this repo.

**Comment by NicoZweifel** [comment]
Let me know if I can help
