### ISSUE TITLE
Scrape Intercom help centers

### ISSUE THREAD

**Issue by tobias-mintlify** [mintlify/mint#278]
## Background

The Mintlify CLI has `scrape-page` and `scrape-section` commands to scrape other documentation websites into MDX format to help people migrate to the Mintlify platform. The commands automatically detect the platform and scrape the pages. Most of the logic to create a page is reusable but actually scraping each docs platform is different. You need to customize the scraping code to the HTML of the platform to know where nav links where and where the content itself is.

## Goal

Scrape Intercom help centres into `.mdx` files. For example: https://www.intercom.com/help/en/

## Tips

Break this up into three PRs.

1. Automatically detect whether a website is an Intercom help center. You will need to update `packages/mintlify/src/scraping/detectFramework.ts`. You can accomplish this by looking for `<meta name="intercom:trackingEvent` in the HTML.
2. Add `scrape-page` to download a single page's content into an MDX file.
3. Add scrape-section` that goes through the navigation to find all the pages and run `scrape-page` on each. Intercom collections should be treated as Mintlify groups when generating the `mint.json`.

See other scrapers for examples. There are helper functions you can use.

## Further Reading

[Cheerio, a library we use to help parse the HTML when scraping](https://cheerio.js.org/)

[Scraper docs](https://github.com/mintlify/mint/blob/main/packages/mintlify/scraper.md)

**Comment by Graviis** [comment]
Im gonna take this one too ⚡️

**Comment by Graviis** [comment]
@tobias-mintlify one question here, do we want to scrape the whole page? You pass: [Intercom](https://www.intercom.com/help/en/) or only sections? pass the link to one collection: eg: [Intercom section](https://www.intercom.com/help/en/collections/382-what-is-intercom)

**Comment by tobias-mintlify** [comment]
Users would need to pass a link to the help center home page when running `scrape-section` so we can see all the collections. The scraper would need to open each section/collection and run recursively.

When scraping a single page with `scrape-page`, users should paste a link directly to the help center article they want.
