### ISSUE TITLE
Warn user in the CLI if files are over 5 Mb

### ISSUE THREAD

**Issue by tobias-mintlify** [mintlify/mint#279]
Mintlify does not support file uploads over 5 Mb. However, the CLI will display an image even if it's over 5 Mb causing users to be confused when the production site doesn't render the image.

The file listener should print a warning when static files are over 5 Mb. Relevant file: `packages/mintlify/src/local-preview/listener/index.ts`

We use chokindar to detect file changes. Ideally we would not copy the file over to the CLI's local Mintlify server when the image is over 5 Mb. That being said, prioritize keeping the CLI fast. Feel free to make the warning async if checking the file size is too slow to do synchronously.

**Comment by Graviis** [comment]
Here's the PR https://github.com/mintlify/mint/pull/281

**Comment by tobias-mintlify** [comment]
Thank you!
