### ISSUE TITLE
Allow specifying type of anchor icons

### ISSUE THREAD

**Issue by tobias-mintlify** [mintlify/mint#338]
We default to duotone icons for anchors. We should add an `iconType` property that accepts `'brands' | 'duotone' | 'light' | 'regular' | 'sharp-solid' | 'solid' | 'thin'` and passes it to the the [Icon component](https://github.com/mintlify/mint/blob/main/client/src/ui/Icon.tsx).

**Comment by Lolly1150** [comment]
Has already been done.

**Comment by tobias-mintlify** [comment]
@Lolly1150 this is about adding the property to `mint.json`, including updating the validation package. You're right the code to display the icons already exists.

**Comment by Lolly1150** [comment]
@tobias-mintlify we can close this?
