### ISSUE TITLE
Table of contents pops in

### ISSUE THREAD

**Issue by tobias-mintlify** [mintlify/mint#381]
After merging https://github.com/mintlify/mint/pull/359 I noticed the table of contents is popping in after the page loads, likely because of how state is being set. We need to have the table of contents pre-render to avoid content shifts.

To test visit [any Mintlify page](https://mintlify.com/docs/development) with a table of contents and refresh. You should see the table of contents is not set so we default to wide mode, then the table of contents pops in.

**Comment by tobias-mintlify** [comment]
@NicoZweifel do you have time to take a look at this today?

**Comment by NicoZweifel** [comment]
Yea I can check it later 👍

**Comment by tobias-mintlify** [comment]
I also noticed the font seems to re-load itself when you click between lots of navigation links really quickly. That causes the default, slightly larger, font to appear for a split second. Feel free to make a separate issue if this looks unrelated to what's causing the table of contents to break.
