### ISSUE TITLE
Remove Segment integration

### ISSUE THREAD

**Issue by tobias-mintlify** [mintlify/mint#418]
Segment is increasing our bundle size when it can't be tree shaken out. No one is using Segment and it's expensive to use for page view tracking so we may as well remove it.

**Comment by davidlinc1** [comment]
Just a heads-up, getting an error about Segment modules missing when I try to run `mintlify-dev` on a fresh `git clone` of the latest. Seemed to work again when I tried reverting to [this commit](https://github.com/mintlify/mint/commit/dc1353732564aa209b5cf0ec605758351e29b8dc)
