### ISSUE TITLE
Clipboard icon is placed incorrectly in code snippets within expandable blocks

### ISSUE THREAD

**Issue by benjamin-shen** [mintlify/mint#94]
**Describe the bug**
Clipboard padding is inconsistent with the rest of the site in code snippets within the expandable content blocks.

**To Reproduce**
Go to https://react.email/docs/contributing and expand "Docs Setup Guide".

**Expected behavior**
The clipboard icon should be within the code snippet container, eg. https://react.email/docs/components/html

**Screenshots**
Desktop:
<img width="1386" alt="image" src="https://user-images.githubusercontent.com/34158284/205999431-65b2fa6e-a642-4c01-822a-39375cd4b11d.png">

Responsive:
<img width="882" alt="image" src="https://user-images.githubusercontent.com/34158284/205999328-b99b350e-4f75-4ff3-a7f1-14e6abff495e.png">

Mobile:
<img width="443" alt="image" src="https://user-images.githubusercontent.com/34158284/206000059-eae87f82-9dad-4d80-a769-ce52ab2d038e.png">

**Device:**
 - OS: macOS, iOS
 - Browser: Opera, DuckDuckGo
 - Version: ?

**Comment by tobias-mintlify** [comment]
Bug was fixed a few weeks ago for most customers. The React Email site is on a legacy version for backwards compatibility with custom component imports. The bug will be resolved when React Email can be bumped back to the latest deployment version.
